/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.MainFrame.f;
import static gui.MainFrame.wybor;
import static gui.VisualisationPanel3.resource;
import javax.swing.JPanel;

/**
 *
 * @author Kuba
 */
public class SettingsPanel extends javax.swing.JPanel {

    
        
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        jLabel2.setText(wybor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Label3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        MercuryLabel = new javax.swing.JLabel();
        EarthLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Label4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        NeptuneLabel = new javax.swing.JLabel();
        OrdinaryLabel = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 80, 30));

        Label3.setBackground(new java.awt.Color(0, 0, 0));
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setText("                       Merkury");
        jPanel6.add(Label3);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                         Ziemia");
        jPanel6.add(jLabel10);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 80, 30));

        MercuryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/merkurymax.png"))); // NOI18N
        MercuryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MercuryLabelMouseClicked(evt);
            }
        });
        jPanel7.add(MercuryLabel);

        EarthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ziemiamax.png"))); // NOI18N
        EarthLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EarthLabelMouseClicked(evt);
            }
        });
        jPanel7.add(EarthLabel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel5);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 80, 30));

        Label4.setBackground(new java.awt.Color(0, 0, 0));
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setText("                       Neptun");
        jPanel9.add(Label4);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("                         Zwykły");
        jPanel9.add(jLabel13);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 80, 30));

        NeptuneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neptunmax.png"))); // NOI18N
        NeptuneLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NeptuneLabelMouseClicked(evt);
            }
        });
        jPanel10.add(NeptuneLabel);

        OrdinaryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zwyklymax.png"))); // NOI18N
        OrdinaryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdinaryLabelMouseClicked(evt);
            }
        });
        jPanel10.add(OrdinaryLabel);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 199;
        gridBagConstraints.ipady = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 97, 68, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 65, 0, 66);
        jPanel1.add(MenuButton, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wybrana ikona:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(154, 65, 0, 66);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 65, 0, 66);
        jPanel1.add(jLabel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EarthLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarthLabelMouseClicked
        resource = getClass().getResource("/images/ziemia.png");
        wybor = "Ziemia";
        jLabel2.setText(wybor);
    }//GEN-LAST:event_EarthLabelMouseClicked

    private void MercuryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MercuryLabelMouseClicked
        resource = getClass().getResource("/images/merkury.png");
        wybor = "Merkury";
        jLabel2.setText(wybor);
    }//GEN-LAST:event_MercuryLabelMouseClicked

    private void NeptuneLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NeptuneLabelMouseClicked
        resource = getClass().getResource("/images/neptun.png");
        wybor = "Neptun";
        jLabel2.setText(wybor);
    }//GEN-LAST:event_NeptuneLabelMouseClicked

    private void OrdinaryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdinaryLabelMouseClicked
        resource = null;
        wybor = "Zwykły";
        jLabel2.setText(wybor);
    }//GEN-LAST:event_OrdinaryLabelMouseClicked

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        JPanel mp = new MenuPanel();
        f.getContentPane().removeAll();
        f.add(mp);
        f.validate();
        f.pack();
        repaint();
    }//GEN-LAST:event_MenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EarthLabel;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel MercuryLabel;
    private javax.swing.JLabel NeptuneLabel;
    private javax.swing.JLabel OrdinaryLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
